"""Change age field from integer to string

Revision ID: b736dc2ae40d
Revises: ae6dd8a9b6ae
Create Date: 2025-07-23 17:15:10.734498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b736dc2ae40d'
down_revision = 'ae6dd8a9b6ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toys', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('toys', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.String(length=50),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
